name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-crates:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: publish package to crates
        run: |
          cargo package
          cargo publish --token ${{ secrets.CARGO_TOKEN }} || true
